### ISSUE TITLE
Build Responsiveness and User-Friendly Home Page

### ISSUE THREAD

**Issue by aligates2107** [aligates2107/-DevHub-Engineers-Portal#1]
## Description: 
The current home page of "DevHub Engineers" requires enhancements to ensure that all content is visible and well-aligned across different screen sizes. The improvements should include the following:

**1. Responsive Design:**

 * Ensure that the header, main content, and image sections adapt seamlessly to various screen sizes (mobile, tablet, and desktop).
 * The navigation menu should be accessible and correctly aligned on smaller screens.
 * Text and images should scale appropriately without overlapping or excessive white space.
**2. Implement Animations:**
 * Use Framer Motion to add subtle animations to the header and main content sections. For example, animate the entry of the text and images on the page load.
  * Consider adding hover effects to the navigation links for an enhanced user experience.
## Requirements:
 * Use Tailwind CSS for styling, with custom CSS as needed.
 * Ensure that animations are smooth and do not negatively impact the page load time.
 * Maintain the current design aesthetics, especially the dark blue and white color scheme, with the branding elements.
 
Resources File Images  and Logo : https://drive.google.com/drive/folders/1U_OD7Jv2iJmZgIbEVSECPPfE1KfZkcH6?usp=sharing

![4](https://github.com/user-attachments/assets/5e33ba1f-7a0b-4c06-b7b6-c732701c5df7)

**Comment by aligates2107** [comment]
Accepted  issue #1

**Comment by AliGates915** [comment]
I accepted the issue #1

**Comment by tejasrok007** [comment]
I accept this issue [https://github.com/aligates2107/-DevHub-Engineers-Portal/issues/1](url)

**Comment by tejasrok007** [comment]
![image](https://github.com/user-attachments/assets/0466c9c8-ba3f-4448-9e6c-8e3f03dbb02b)
i completed the work but i dont know to add a pull request i just cloned the project and did the work but i dont know why the option to pull request is not coming .I also made it dynamic watch this
![image](https://github.com/user-attachments/assets/bac80ae6-0b32-4d0d-99cc-c12ac3f0e71d)
Do i need to add something more so that the pull request gets accepted?

**Comment by tejasrok007** [comment]
I figured it out and have added the pull request
Please review it and let me know

**Comment by aligates2107** [comment]
> I figured it out and have added the pull request Please review it and let me know

@tejasrok007  see issue #5
