### ISSUE TITLE
Build the Home Page change the background color  

### ISSUE THREAD

**Issue by aligates2107** [aligates2107/-DevHub-Engineers-Portal#5]
1. Change the background-color, this bg-color is apply all the webiste, see  the google drive file
https://docs.google.com/document/d/19H0OS_bgCBkOBwzjj80yzPgCBtlqfkihOvr-nSAqs4A/edit?usp=sharing
* root {
   Bg-Color:  #232730
}
 * Home-Hero-Text: #ffde59
2. Change the  logo 
3. In the mobile device, 1st All the text is show then image is show
4. Logo
    ![logo devHub Engineer’s](https://github.com/user-attachments/assets/e9bf144d-b940-4690-bff3-619ee7ae144c)
5. Home page UI Design
    ![Home page](https://github.com/user-attachments/assets/98432bec-4c18-45fe-9279-c4ead393ca30)

**Comment by tejasrok007** [comment]
Hey hi again sorry for commenting after a long time Can i complete this?

**Comment by aligates2107** [comment]
yes

> Hey hi again sorry for commenting after a long time Can i complete this?

Yeah, You can complete this.

**Comment by aligates2107** [comment]
> yes
> 
> > Hey hi again sorry for commenting after a long time Can i complete this?
> 
> Yeah, You can complete this.

I am working on different pages. You build the Header, Home, etc.

**Comment by aligates2107** [comment]
See issue #7 
@tejasrok007
